language: node_js
node_js:
  - 6.9.1
sudo: required
cache:
  directories:
    - ~/.nvm
    - node_modules
services:
  - docker
git:
  depth: 1
env:
  global:
    - RELEASE_BRANCH="master"
    - DOCKER_HUB_ACCOUNT=edenlabllc
    - MAIN_BRANCHES="master develop"
    # DOCKER_PASSWORD GITHUB_TOKEN
    - secure: "FpErZwMxV7k5PW/fv7xN9gVcIs1C2irbFr2NRPrQIqprSAa0AY/CytAYi2wnjR51TltA7TCPMmAAlLWFAxOxgr2xiU2F0rhRplxX2d9WmRdfO+Fhd/irl+uJBd61MEY16i8oxGxz5IQc/ub/OWr8Uqcuqv+0RpeInvDsszcMSxk4tSPzNtrlC3YcxBUEDDGYYr97BHB84I/ylZisjP2836RbayxaEkyB5qdFADuQpf1fkosQfm7l1Vohh2u7jJOtHZB0cdUvdhKKmqcCIecH9xqukbSAbxWWbjI8rmoMxYg6xvJRLjUZ6r5gMIoqU+G1y+kvruI75XwHZJOSFChzwEi/Bo/wj7jjxHz5SC8dVhUdLRi6hJmtphn4TFJqyc/bhFLd3dynUsWKo56cxqP2jINRl1DnSF5cDattT8ZLmCC87k9AQNmeBQU9DYLvMlpcZ1YMzJ2E9ORE0a4I4MVoOlnFaiANqVgqUSa2o4ofTKUxQnoOuybx48aU+aTWD/jmJOnQQ5bsQui76uqdhrKlGw9mrl1tPbDH2aUJjBtiDQ0PdNNcqzuIMGSK4cyM2GossXTeRTQrM6EFlZJH7p9PcDgpB2C0FS5UqyubPs6WkG+jhyLNSjPg6va5/9SPlalyf1ZfItBHId0CJHN3lylYbsACrPxehscC3IcaamzFJAU="
    - secure: "HlzWelHFXCT7Q0Tt0gVYmwnThEB5SbZtg+0xvDFP6zIl3nNosD59YSNN6/ABRFVCmXwO/+8SY4GLNA2uqrQ4R6V0R4KTGnDF3BuUg7Ymp9rHw59VVzxSn8yR4gEY+CGNXSy4M/DGvojiHn4krxrqZRTGFSjcvgi8BOwrOhUnnRr4KwMyn5bav7XcnX3XXVALXG/6JUi5Veov4zou8iU7H9W+bHcRVbKUdJxRaZ9WB7zSx4pCyXpKPY7T4h3xPlcF1KMt5lFlFsp8bpHiCk4PW9kTJ55qQmm3csw/Yq60PSnmqLDArnVmVytn+HqzVxqaz1tpKjOZCUkrKsqMAZfBWn3IlK9Ix5MOy7z+cHjOg8O5XCHB8nw298+I5zqWR+Gq8swZmpqHtwT5bbD0jEtEEtVqBUMlp6RfCqx8sF5f0HJn9OXRuJhg9fg5+P2NM7hpWRG7+Yq5TGuHyTkXTOBlW9A8TVF4lbHJ5zhwhbDoMdcJyb4tFQmbFSATTMQ9Bb4tYUFfZB/xt6S2+MJn2+Uui4Y34Xfs1uLEPz/jR4TL1o+LDmVM8zbl2LcEv1jPrxI0R3Z/aQK9bU9ngpaSXyCPwcwTR97XqSsNpxNBOoFCYfVrDZ7mjl5rokV+AdzXG6oc/6GDKNxLGw+gC/oJVMRsVKQBDbAEd6I0J40h2oTcW88="
before_script:
  - chmod -R +x bin
  - ./bin/version-increment.sh && ./bin/build.sh && ./bin/start.sh || { exit 1; }
after_success:
  - ./bin/ci/push.sh
